-- CRIANDO OBJETO NO BD
CREATE SCHEMA `SIS2402`;

-- CRIANDO A TABELA
CREATE TABLE `SIS2402`.`CLIENTES`(
    `ID_CLIENTE` INT NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(100) NOT NULL,
    `EMAIL` VARCHAR(320) NOT NULL,
    `DATA_NASCIMENTO` DATE NOT NULL,
    `SEXO_GENERO` VARCHAR(20) NULL DEFAULT 'NAO ESPECIFICADO',
    `CEP` INT(8) NOT NULL,
    `RUA` VARCHAR(50) NOT NULL,
    `NUMERO` INT(10) NOT NULL,
    `BAIRRO` VARCHAR(50) NOT NULL,
    `CIDADE` VARCHAR(50) NOT NULL,
    `UF` CHAR(2) NOT NULL,
    `PAIS` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`ID_CLIENTE`)
);
